/**
 * CSV Parser for ECG Data
 * Parses the CSV file generated by Flutter PDF service
 */

import type { ECGDataPoint, ECGLead, ECGData, PatientInfo, ECGSettings } from '../types';
import { LEAD_NAMES } from './constants';

export class CSVParser {
  /**
   * Parse CSV file content into ECG data structure
   */
  static parseCSV(csvContent: string): ECGData {
    const lines = csvContent.trim().split('\n');

    if (lines.length < 2) {
      throw new Error('CSV file is empty or invalid');
    }

    // Parse header
    const header = lines[0].split(',');
    this.validateHeader(header);

    // Parse data points
    const dataPoints: ECGDataPoint[] = [];

    for (let i = 1; i < lines.length; i++) {
      const values = lines[i].split(',');

      if (values.length !== header.length) {
        console.warn(`Skipping malformed line ${i + 1}`);
        continue;
      }

      const dataPoint: ECGDataPoint = {
        sample_index: parseInt(values[0]),
        x_coord: parseFloat(values[1]),
        lead: parseInt(values[2]),
        lead_name: values[3].trim(),
        filtered_value: parseFloat(values[4]),
        adjusted_y: parseFloat(values[5]),
        plot_y: parseFloat(values[6]),
      };

      dataPoints.push(dataPoint);
    }

    // Group data points by lead
    const leads = this.groupByLead(dataPoints);

    // Extract settings from data
    const settings: ECGSettings = {
      gain: 2, // Default, can be extracted from filename if needed
      filterType: '150Hz', // Default
      sampleRate: 250,
      totalSamples: 6500,
    };

    return {
      leads,
      settings,
      timestamp: new Date(),
    };
  }

  /**
   * Validate CSV header matches expected format
   */
  private static validateHeader(header: string[]): void {
    const expectedHeaders = [
      'sample_index',
      'x_coord',
      'lead',
      'lead_name',
      'filtered_value',
      'adjusted_y',
      'plot_y',
    ];

    for (let i = 0; i < expectedHeaders.length; i++) {
      if (header[i]?.trim() !== expectedHeaders[i]) {
        throw new Error(
          `Invalid CSV header. Expected "${expectedHeaders[i]}" at column ${i + 1}, got "${header[i]}"`
        );
      }
    }
  }

  /**
   * Group data points by lead index
   */
  private static groupByLead(dataPoints: ECGDataPoint[]): ECGLead[] {
    const leadMap = new Map<number, ECGDataPoint[]>();

    // Initialize all 12 leads
    for (let i = 0; i < 12; i++) {
      leadMap.set(i, []);
    }

    // Group data points
    for (const point of dataPoints) {
      const leadData = leadMap.get(point.lead);
      if (leadData) {
        leadData.push(point);
      }
    }

    // Convert map to array of ECGLead objects
    const leads: ECGLead[] = [];
    leadMap.forEach((dataPoints, leadIndex) => {
      // Sort by sample_index to ensure correct order
      dataPoints.sort((a, b) => a.sample_index - b.sample_index);

      leads.push({
        leadIndex,
        leadName: LEAD_NAMES[leadIndex],
        dataPoints,
      });
    });

    return leads;
  }

  /**
   * Extract patient info from filename
   * Format: patientName_DD_Month_YYYY_HH_MM_SS_ecg_data.csv
   */
  static extractPatientInfoFromFilename(filename: string): Partial<PatientInfo> {
    const parts = filename.replace('_ecg_data.csv', '').split('_');

    if (parts.length >= 7) {
      const name = parts[0];
      const day = parts[1];
      const month = parts[2];
      const year = parts[3];
      const hour = parts[4];
      const minute = parts[5];

      return {
        name,
        id: `${name}-${day}${month}${year}`,
        dob: `${day} ${month} ${year}`,
      };
    }

    return {
      name: 'Unknown',
      id: 'N/A',
    };
  }

  /**
   * Read file and parse CSV
   */
  static async parseFile(file: File): Promise<ECGData> {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();

      reader.onload = (event) => {
        try {
          const csvContent = event.target?.result as string;
          const ecgData = this.parseCSV(csvContent);

          // Extract patient info from filename
          const patientInfo = this.extractPatientInfoFromFilename(file.name);
          ecgData.patientInfo = patientInfo as PatientInfo;

          resolve(ecgData);
        } catch (error) {
          reject(error);
        }
      };

      reader.onerror = () => {
        reject(new Error('Failed to read file'));
      };

      reader.readAsText(file);
    });
  }
}
